apiVersion: v1
kind: Service
metadata:
  name: mattermost-gitlab-to-keycloak-oauth-adapter
  namespace: mattermost
spec:
  selector:
    app: mattermost-gitlab-to-keycloak-oauth-adapter
    service: mattermost-gitlab-to-keycloak-oauth-adapter
  type: ClusterIP

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
