name: "mattermost-gitlab-to-keycloak-oauth-adapter"

deployment:
  replicas: 1
  annotations: {}
  labels: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  image:
    repository: "ghcr.io/chloyka/mattermost-gitlab-to-keycloak-oauth-adapter"
    tag: "master"
    pullPolicy: IfNotPresent
  env: []

service:
  name: "mattermost-gitlab-to-keycloak-oauth-adapter"
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: "nginx"
  tls: []
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  rules:
    - host: your-hostname.com
      http:
        paths:
          - path: /